{
 "title": "Sustainability Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n<h1 style=\"text-align: center; color: #2ecc71\">Application Performance Metrics</h1>"
   }
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")/5 FROM \"jmeter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "\n\n<h1 style=\"text-align: center; color: #2ecc71\">Application Environmental Metrics</h1>"
   }
  },
  {
   "title": "Energy saving from x86 to LinuxONE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1s",
        "sum"
       ],
       "text": "groupBy(1s, sum)",
       "$$hashKey": "object:1375"
      }
     ],
     "group": { "filter": "x86 servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "total power in use" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "aggregation": { "key": "MEAN", "label": "MEAN" },
     "aggregationFunction": { "label": "MEAN" },
     "entityQuery": "zhmc",
     "entityType": { "key": "zhmcCpc", "label": "zHMC System" },
     "metric": {
      "aggregations": [
       { "key": "MEAN", "label": "MEAN" },
       { "key": "SUM", "label": "SUM" }
      ],
      "description": "dpmPowerConsumptionWatts",
      "entityType": "zhmcCpc",
      "key": "dpmPowerConsumptionWatts",
      "label": "DPM Power Consumption Watts"
     },
     "metricCategory": {
      "key": 0,
      "label": "Infrastructure built-in metrics"
     },
     "timeInterval": { "key": "60000", "label": "1min" }
    }
   ]
  },
  {
   "title": "Application Energy Consumption Before Migration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10s",
        "sum"
       ],
       "text": "groupBy(10s, sum)",
       "$$hashKey": "object:187"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "total power in use" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Application Energy Consumption After Migration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": { "key": "MEAN", "label": "MEAN" },
     "aggregationFunction": { "label": "MEAN" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "entityQuery": "zhmc",
     "entityType": { "key": "zhmcCpc", "label": "zHMC System" },
     "metric": {
      "aggregations": [
       { "key": "MEAN", "label": "MEAN" },
       { "key": "SUM", "label": "SUM" }
      ],
      "description": "envPowerConsumptionWatts",
      "entityType": "zhmcCpc",
      "key": "envPowerConsumptionWatts",
      "label": "Environment Power Consumption Watts"
     },
     "metricCategory": {
      "key": 0,
      "label": "Infrastructure built-in metrics"
     },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp",
     "timeInterval": { "key": "60000", "label": "1min" }
    }
   ]
  },
  {
   "title": "Application Energy Consumption Before Migration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kg/h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10s",
        "sum"
       ],
       "text": "groupBy(10s, sum)",
       "$$hashKey": "object:214"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "total power in use" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Application Carbon Emissioon After Migration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kg/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": { "key": "MEAN", "label": "MEAN" },
     "aggregationFunction": { "label": "MEAN" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "entityQuery": "zhmc",
     "entityType": { "key": "zhmcCpc", "label": "zHMC System" },
     "metric": {
      "aggregations": [
       { "key": "MEAN", "label": "MEAN" },
       { "key": "SUM", "label": "SUM" }
      ],
      "description": "envPowerConsumptionWatts",
      "entityType": "zhmcCpc",
      "key": "envPowerConsumptionWatts",
      "label": "Environment Power Consumption Watts"
     },
     "metricCategory": {
      "key": 0,
      "label": "Infrastructure built-in metrics"
     },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp",
     "timeInterval": { "key": "60000", "label": "1min" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "\n\n<h1 style=\"text-align: center; color: #2ecc71\">Infrastructure Monitoring Metrics</h1>"
   }
  },
  {
   "title": "x86 Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10s",
        "sum"
       ],
       "text": "groupBy(10s, sum)",
       "$$hashKey": "object:106"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "total power in use" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LinuxONE Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "aggregation": { "key": "MEAN", "label": "MEAN" },
     "aggregationFunction": { "label": "MEAN" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "entityQuery": "zhmc",
     "entityType": { "key": "zhmcCpc", "label": "zHMC System" },
     "metric": {
      "aggregations": [
       { "key": "MEAN", "label": "MEAN" },
       { "key": "SUM", "label": "SUM" }
      ],
      "description": "envPowerConsumptionWatts",
      "entityType": "zhmcCpc",
      "key": "envPowerConsumptionWatts",
      "label": "Environment Power Consumption Watts"
     },
     "metricCategory": {
      "key": 0,
      "label": "Infrastructure built-in metrics"
     },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp",
     "timeInterval": { "key": "60000", "label": "1min" }
    }
   ]
  },
  {
   "title": "x86 cpu cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-01 CPU threads" ],
       "text": "setAlias(x3550m4-01 CPU threads)",
       "$$hashKey": "object:361"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-01" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-02 CPU threads" ],
       "text": "setAlias(x3550m4-02 CPU threads)",
       "$$hashKey": "object:382"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-02" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-03 CPU threads" ],
       "text": "setAlias(x3550m4-03 CPU threads)",
       "$$hashKey": "object:403"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-03" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-04 CPU threads" ],
       "text": "setAlias(x3550m4-04 CPU threads)",
       "$$hashKey": "object:424"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-04" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-05 CPU threads" ],
       "text": "setAlias(x3550m4-05 CPU threads)",
       "$$hashKey": "object:445"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-05" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-06 CPU threads" ],
       "text": "setAlias(x3550m4-06 CPU threads)",
       "$$hashKey": "object:466"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-06" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-07 CPU threads" ],
       "text": "setAlias(x3550m4-07 CPU threads)",
       "$$hashKey": "object:487"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-07" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-09 CPU threads" ],
       "text": "setAlias(x3550m4-09 CPU threads)",
       "$$hashKey": "object:508"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-09" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-10 CPU threads" ],
       "text": "setAlias(x3550m4-10 CPU threads)",
       "$$hashKey": "object:529"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-10" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-02 CPU threads" ],
       "text": "setAlias(x3550m3-02 CPU threads)",
       "$$hashKey": "object:550"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-02" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-03 CPU threads" ],
       "text": "setAlias(x3550m3-03 CPU threads)",
       "$$hashKey": "object:571"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-03" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-04 CPU threads" ],
       "text": "setAlias(x3550m3-04 CPU threads)",
       "$$hashKey": "object:592"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-04" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-05 CPU threads" ],
       "text": "setAlias(x3550m3-05 CPU threads)",
       "$$hashKey": "object:613"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-05" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-06 CPU threads" ],
       "text": "setAlias(x3550m3-06 CPU threads)",
       "$$hashKey": "object:634"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-06" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-07 CPU threads" ],
       "text": "setAlias(x3550m3-07 CPU threads)",
       "$$hashKey": "object:655"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-07" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-08 CPU threads" ],
       "text": "setAlias(x3550m3-08 CPU threads)",
       "$$hashKey": "object:676"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-08" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-10 CPU threads" ],
       "text": "setAlias(x3550m3-10 CPU threads)",
       "$$hashKey": "object:697"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-10" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-01 CPU threads" ],
       "text": "setAlias(x3650m4-01 CPU threads)",
       "$$hashKey": "object:718"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3650m4-01" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-02 CPU threads" ],
       "text": "setAlias(x3650m4-02 CPU threads)",
       "$$hashKey": "object:739"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3650m4-02" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-03 CPU threads" ],
       "text": "setAlias(x3650m4-03 CPU threads)",
       "$$hashKey": "object:760"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3650m4-03" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-03 CPU threads" ],
       "text": "setAlias(x3650m4-03 CPU threads)",
       "$$hashKey": "object:781"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m5-01" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total x86 cpu cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-01 CPU threads" ],
       "text": "setAlias(x3550m4-01 CPU threads)",
       "$$hashKey": "object:928"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-01" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-02 CPU threads" ],
       "text": "setAlias(x3550m4-02 CPU threads)",
       "$$hashKey": "object:949"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-02" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-03 CPU threads" ],
       "text": "setAlias(x3550m4-03 CPU threads)",
       "$$hashKey": "object:970"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-03" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-04 CPU threads" ],
       "text": "setAlias(x3550m4-04 CPU threads)",
       "$$hashKey": "object:991"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-04" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-05 CPU threads" ],
       "text": "setAlias(x3550m4-05 CPU threads)",
       "$$hashKey": "object:1012"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-05" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-06 CPU threads" ],
       "text": "setAlias(x3550m4-06 CPU threads)",
       "$$hashKey": "object:1033"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-06" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-07 CPU threads" ],
       "text": "setAlias(x3550m4-07 CPU threads)",
       "$$hashKey": "object:1054"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-07" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-09 CPU threads" ],
       "text": "setAlias(x3550m4-09 CPU threads)",
       "$$hashKey": "object:1075"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-09" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m4-10 CPU threads" ],
       "text": "setAlias(x3550m4-10 CPU threads)",
       "$$hashKey": "object:1096"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m4-10" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-02 CPU threads" ],
       "text": "setAlias(x3550m3-02 CPU threads)",
       "$$hashKey": "object:1117"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-02" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-03 CPU threads" ],
       "text": "setAlias(x3550m3-03 CPU threads)",
       "$$hashKey": "object:1138"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-03" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-04 CPU threads" ],
       "text": "setAlias(x3550m3-04 CPU threads)",
       "$$hashKey": "object:1159"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-04" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-05 CPU threads" ],
       "text": "setAlias(x3550m3-05 CPU threads)",
       "$$hashKey": "object:1180"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-05" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-06 CPU threads" ],
       "text": "setAlias(x3550m3-06 CPU threads)",
       "$$hashKey": "object:1201"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-06" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-07 CPU threads" ],
       "text": "setAlias(x3550m3-07 CPU threads)",
       "$$hashKey": "object:1222"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-07" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-08 CPU threads" ],
       "text": "setAlias(x3550m3-08 CPU threads)",
       "$$hashKey": "object:1243"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-08" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3550m3-10 CPU threads" ],
       "text": "setAlias(x3550m3-10 CPU threads)",
       "$$hashKey": "object:1264"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m3-10" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-01 CPU threads" ],
       "text": "setAlias(x3650m4-01 CPU threads)",
       "$$hashKey": "object:1285"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3650m4-01" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-02 CPU threads" ],
       "text": "setAlias(x3650m4-02 CPU threads)",
       "$$hashKey": "object:1306"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3650m4-02" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-03 CPU threads" ],
       "text": "setAlias(x3650m4-03 CPU threads)",
       "$$hashKey": "object:1327"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3650m4-03" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "x3650m4-03 CPU threads" ],
       "text": "setAlias(x3650m4-03 CPU threads)",
       "$$hashKey": "object:1348"
      }
     ],
     "group": { "filter": " x86 servers" },
     "host": { "filter": "-x3550m5-01" },
     "item": { "filter": "VMware: CPU threads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LinuxONE IFL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zhmc_cpc_ifl_processor_count{cpc=\"linux1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Utilization - x86",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": { "key": "MEAN", "label": "MEAN" },
     "aggregationFunction": { "label": "MEAN" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "entityQuery": "vsphere",
     "entityType": { "key": "host", "label": "Host" },
     "metric": {
      "aggregations": [
       { "key": "MEAN", "label": "MEAN" },
       { "key": "SUM", "label": "SUM" }
      ],
      "description": "cpu.used",
      "entityType": "host",
      "key": "cpu.used",
      "label": "Used"
     },
     "metricCategory": {
      "key": 0,
      "label": "Infrastructure built-in metrics"
     },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp",
     "timeInterval": { "key": "60000", "label": "1min" }
    }
   ]
  },
  {
   "title": "Average IFL Utilization - LinuxONE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": { "key": "MEAN", "label": "MEAN" },
     "aggregationFunction": { "label": "SUM" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "entityQuery": "zhmc",
     "entityType": { "key": "zhmcCpc", "label": "zHMC System" },
     "metric": {
      "aggregations": [
       { "key": "MEAN", "label": "MEAN" },
       { "key": "SUM", "label": "SUM" }
      ],
      "description": "dpmIflAllProcessorUsage",
      "entityType": "zhmcCpc",
      "key": "dpmIflAllProcessorUsage",
      "label": "DPM Ifl All Processor Usage"
     },
     "metricCategory": {
      "key": 0,
      "label": "Infrastructure built-in metrics"
     },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp",
     "timeInterval": { "key": "60000", "label": "1min" }
    }
   ]
  }
 ]
}